version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - botnet

  bot:
    build: .
    depends_on:
      - db
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      OMDB_API_KEY: ${OMDB_API_KEY}
      APPLICATION_ID: ${APPLICATION_ID}
      
    volumes:
      - .:/app
    command: python -m rumble
    networks:
      - botnet

volumes:
  postgres_data:

networks:
  botnet:
